#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/fleur

PRODUCT_COPY_FILES += \
    vendor/xiaomi/fleur/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/apdb/APDB_MT6785_S01__W2248:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6785_S01__W2248 \
    vendor/xiaomi/fleur/proprietary/vendor/etc/apdb/APDB_MT6785_S01__W2248_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6785_S01__W2248_ENUM \
    vendor/xiaomi/fleur/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/camerabooster.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camerabooster.json \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/com.xiaomi.dcal.wd.1.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wd.1.golden \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/com.xiaomi.dcal.wd.2.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wd.2.golden \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/com.xiaomi.dcal.wd.3.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wd.3.golden \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.1.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.1.golden \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.2.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.2.golden \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.3.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.3.golden \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/dof_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dof_mecp.bin \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/intsense_config_undistort_k7p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/intsense_config_undistort_k7p.bin \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/intsense_config_undistort_k7s.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/intsense_config_undistort_k7s.bin \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/mibokeh_mt6853_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_mt6853_opencl.bin \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/mibokeh_mt6853_parameter.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_mt6853_parameter.bin \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/cap_ldc_model/ldc_cap_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/cap_ldc_model/ldc_cap_cache \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/cap_ldc_model/ldc_cap_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/cap_ldc_model/ldc_cap_model \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/cap_ldc_model/ldc_cap_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/cap_ldc_model/ldc_cap_policy \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/dof_model/capture_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/dof_model/capture_cache \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/dof_model/capture_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/dof_model/capture_model \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/dof_model/capture_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/dof_model/capture_policy \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/rt_ldc_model/ldc_pre_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_ldc_model/ldc_pre_cache \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/rt_ldc_model/ldc_pre_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_ldc_model/ldc_pre_model \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/rt_ldc_model/ldc_pre_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_ldc_model/ldc_pre_policy \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/rt_model/preview_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_cache \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/rt_model/preview_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_model \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/model/rt_model/preview_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_policy \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/fleur/proprietary/vendor/etc/dsi_panel_k7s_38_0c_0a_video_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_panel_k7s_38_0c_0a_video_mi.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/dsi_panel_k7s_38_0c_0b_video_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_panel_k7s_38_0c_0b_video_mi.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/elliptic_sensor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic_sensor.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service.beanpod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service.beanpod.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/android.hardware.tetheroffload-V1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.tetheroffload-V1-service.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.batterysecret.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.batterysecret.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/microtrust.bp_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.bp_kmsetkey_ca.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/microtrust.init_thh.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.init_thh.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent-service.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/vendor.microtrust.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.microtrust.hardware.soter@1.0-service.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/vendor.microtrust.hardware.thh@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.microtrust.hardware.thh@2.0-service.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ipsec/ipsec.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ssl/openssl.cnf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/ipsec/strongswan.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/strongswan.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/screen_light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/screen_light.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/xiaomi/fleur/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/xiaomi/fleur/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/smartpa_param/fsmsdg_params.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/fsmsdg_params.bin \
    vendor/xiaomi/fleur/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-hp-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-hp-mgame.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-hp-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-hp-normal.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-navigation.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermal-videochat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-videochat.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/fleur/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/xiaomi/fleur/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/Conf_MultipleTest.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/Conf_MultipleTest.ini \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_2_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_2_1.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_2a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_2a_1.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_LONG_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_LONG_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_M_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_M_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_Q_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_Q_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_Z_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_Z_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_cali_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_cali_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_need_setup_M_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_need_setup_M_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_need_setup_Q_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_need_setup_Q_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_high_f0_need_setup_Z_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_high_f0_need_setup_Z_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_LONG_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_LONG_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_M_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_M_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_Q_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_Q_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_Z_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_Z_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_cali_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_cali_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_need_setup_M_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_need_setup_M_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_need_setup_Q_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_need_setup_Q_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_low_f0_need_setup_Z_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_low_f0_need_setup_Z_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_LONG_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_LONG_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_M_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_M_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_Q_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_Q_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_Z_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_Z_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_cali_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_cali_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_need_setup_M_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_need_setup_M_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_need_setup_Q_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_need_setup_Q_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw8622_mid_f0_need_setup_Z_cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622_mid_f0_need_setup_Z_cfg.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/aw87xxx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_acf.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/focaltech_ts_fw_samsung.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_samsung.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/fs1815.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1815.fsm \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2280.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2300.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2280.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2300.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/soc2_2_ram_bt_2_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_2_1_hdr.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/soc2_2_ram_bt_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_2a_1_hdr.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/soc2_2_ram_mcu_2_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_2_1_hdr.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/soc2_2_ram_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_2a_1_hdr.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/soc2_2_ram_wifi_2_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_2_1_hdr.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/soc2_2_ram_wifi_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_2a_1_hdr.bin \
    vendor/xiaomi/fleur/proprietary/vendor/firmware/st21nfc_fw7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw7.bin \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/0102030405060708090a0b0c0d0e0f10.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/0102030405060708090a0b0c0d0e0f10.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/05120000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/05120000000000000000000000000000.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/06090000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/06090000000000000000000000000000.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/08010203000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08010203000000000000000000000000.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/08030000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08030000000000000000000000000000.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/08040000000000000000000000003419.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08040000000000000000000000003419.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/08050000000000000000000000003419.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08050000000000000000000000003419.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/08110000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08110000000000000000000000000000.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/5020170115e016302017012521300000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5020170115e016302017012521300000.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/8aaaf201246000007143fe4f7c823c80.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8aaaf201246000007143fe4f7c823c80.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/abcd270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/abcd270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/xiaomi/fleur/proprietary/vendor/thh/ta/isee_model.json:$(TARGET_COPY_OUT_VENDOR)/thh/ta/isee_model.json

PRODUCT_PACKAGES += \
    libbwc \
    libfile_op \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libladder \
    libmtk_drvb \
    libmtkcutils \
    libmtkproperty \
    libmtkrillog \
    libnvram \
    libnvram_sec \
    libverno \
    audio.primary.mt6781 \
    audio.r_submix.mt6781 \
    sound_trigger.primary.default \
    libMtkSpeechEnh \
    lib_iir \
    lib_speech_enh \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libcvsd_mtk \
    libfgauge_gm30 \
    libfsmsmartpaparse \
    libmsbc_mtk \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libnxp_extamp_intf \
    librt_extamp_intf \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libvcodec_oal \
    libvcodec_utility \
    libvcodecdrv \
    libvcodecdrv_header_stub \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvpu5 \
    libvpud_vcodec \
    libvt_custom \
    vendor.mediatek.hardware.audio@7.1 \
    APUWareUtilsAidlServer \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    gc02m1_macro_aac_mipi_raw_IdxMgr \
    gc02m1_macro_aac_mipi_raw_tuning \
    gc02m1_macro_ofilm_mipi_raw_IdxMgr \
    gc02m1_macro_ofilm_mipi_raw_tuning \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    consumerir.mt6781 \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    gatekeeper.beanpod \
    gps.default \
    hwcomposer.mtk_common \
    sensors.elliptic@2.0 \
    sensors.mt6781 \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.camera.postproc@1.0-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    vulkan.mali \
    imx355_ultra_ofilm_mipi_raw_IdxMgr \
    imx355_ultra_ofilm_mipi_raw_tuning \
    imx471_front_ofilm_mipi_raw_IdxMgr \
    imx471_front_ofilm_mipi_raw_tuning \
    imx471_front_sunny_mipi_raw_IdxMgr \
    imx471_front_sunny_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libAVCSecureVencCA \
    libCamera_gc02m1macroaacmipiraw_Default_Capture \
    libCamera_gc02m1macroaacmipiraw_Default_Preview \
    libCamera_gc02m1macroaacmipiraw_Default_Video \
    libCamera_gc02m1macroaacmipiraw_Flash_Capture \
    libCamera_gc02m1macroaacmipiraw_Scene_Capture \
    libCamera_gc02m1macroaacmipiraw_Scene_Capture_Zoom1 \
    libCamera_gc02m1macroaacmipiraw_Scene_Capture_Zoom2 \
    libCamera_gc02m1macroaacmipiraw_Scene_Preview \
    libCamera_gc02m1macroaacmipiraw_Scene_Preview_Zoom1 \
    libCamera_gc02m1macroaacmipiraw_Scene_Preview_Zoom2 \
    libCamera_gc02m1macroaacmipiraw_Scene_Professional_Capture \
    libCamera_gc02m1macroaacmipiraw_Scene_Professional_Preview \
    libCamera_gc02m1macroaacmipiraw_Video \
    libCamera_gc02m1macroofilmmipiraw_Default_Capture \
    libCamera_gc02m1macroofilmmipiraw_Default_Preview \
    libCamera_gc02m1macroofilmmipiraw_Default_Video \
    libCamera_gc02m1macroofilmmipiraw_Flash_Capture \
    libCamera_gc02m1macroofilmmipiraw_Scene_Capture \
    libCamera_gc02m1macroofilmmipiraw_Scene_Capture_Zoom1 \
    libCamera_gc02m1macroofilmmipiraw_Scene_Capture_Zoom2 \
    libCamera_gc02m1macroofilmmipiraw_Scene_Preview \
    libCamera_gc02m1macroofilmmipiraw_Scene_Preview_Zoom1 \
    libCamera_gc02m1macroofilmmipiraw_Scene_Preview_Zoom2 \
    libCamera_gc02m1macroofilmmipiraw_Scene_Professional_Capture \
    libCamera_gc02m1macroofilmmipiraw_Scene_Professional_Preview \
    libCamera_gc02m1macroofilmmipiraw_Video \
    libCamera_imx355ultraofilmmipiraw_EIS_Video_1080P \
    libCamera_imx355ultraofilmmipiraw_EIS_Video_720P \
    libCamera_imx355ultraofilmmipiraw_Face_Capture \
    libCamera_imx355ultraofilmmipiraw_Face_Preview \
    libCamera_imx355ultraofilmmipiraw_Flash_Capture \
    libCamera_imx355ultraofilmmipiraw_HDR_Face_Capture \
    libCamera_imx355ultraofilmmipiraw_HDR_Scene_Capture \
    libCamera_imx355ultraofilmmipiraw_LLHDR_Face_Capture \
    libCamera_imx355ultraofilmmipiraw_LLHDR_Scene_Capture \
    libCamera_imx355ultraofilmmipiraw_Portrait_Capture \
    libCamera_imx355ultraofilmmipiraw_Portrait_Preview \
    libCamera_imx355ultraofilmmipiraw_Professional_Capture \
    libCamera_imx355ultraofilmmipiraw_Professional_Preview \
    libCamera_imx355ultraofilmmipiraw_Scene_Capture \
    libCamera_imx355ultraofilmmipiraw_Scene_Preview \
    libCamera_imx355ultraofilmmipiraw_SuperNightRaw_Capture \
    libCamera_imx355ultraofilmmipiraw_SuperNightRaw_Preview \
    libCamera_imx355ultraofilmmipiraw_Video_1080P \
    libCamera_imx355ultraofilmmipiraw_Video_720P \
    libCamera_imx355ultraofilmmipiraw_Zoom1_Video_1080P \
    libCamera_imx355ultraofilmmipiraw_Zoom1_Video_720P \
    libCamera_imx355ultraofilmmipiraw_Zoom2_Video_1080P \
    libCamera_imx355ultraofilmmipiraw_Zoom2_Video_720P \
    libCamera_imx355ultraofilmmipiraw_Zoom_Capture \
    libCamera_imx355ultraofilmmipiraw_Zoom_Preview \
    libCamera_imx471frontofilmmipiraw_3rd_Capture \
    libCamera_imx471frontofilmmipiraw_3rd_Preview \
    libCamera_imx471frontofilmmipiraw_3rd_Video \
    libCamera_imx471frontofilmmipiraw_Face_Capture \
    libCamera_imx471frontofilmmipiraw_FrontLight_Capture \
    libCamera_imx471frontofilmmipiraw_FrontLight_Preview \
    libCamera_imx471frontofilmmipiraw_HDR_Capture \
    libCamera_imx471frontofilmmipiraw_Panorama_Capture \
    libCamera_imx471frontofilmmipiraw_Panorama_Preview \
    libCamera_imx471frontofilmmipiraw_Portrait_Preview \
    libCamera_imx471frontofilmmipiraw_Scene_Preview \
    libCamera_imx471frontofilmmipiraw_Video_1080P_60fps \
    libCamera_imx471frontofilmmipiraw_Video_1080P_EIS \
    libCamera_imx471frontofilmmipiraw_Video_720P_EIS \
    libCamera_imx471frontofilmmipiraw_XTS_Capture \
    libCamera_imx471frontsunnymipiraw_3rd_Capture \
    libCamera_imx471frontsunnymipiraw_3rd_Preview \
    libCamera_imx471frontsunnymipiraw_3rd_Video \
    libCamera_imx471frontsunnymipiraw_Face_Capture \
    libCamera_imx471frontsunnymipiraw_FrontLight_Capture \
    libCamera_imx471frontsunnymipiraw_FrontLight_Preview \
    libCamera_imx471frontsunnymipiraw_HDR_Capture \
    libCamera_imx471frontsunnymipiraw_Panorama_Capture \
    libCamera_imx471frontsunnymipiraw_Panorama_Preview \
    libCamera_imx471frontsunnymipiraw_Portrait_Preview \
    libCamera_imx471frontsunnymipiraw_Scene_Preview \
    libCamera_imx471frontsunnymipiraw_Video_1080P_60fps \
    libCamera_imx471frontsunnymipiraw_Video_1080P_EIS \
    libCamera_imx471frontsunnymipiraw_Video_720P_EIS \
    libCamera_imx471frontsunnymipiraw_XTS_Capture \
    libCamera_ov02b1bdepthsunny2mipiraw_Default_Capture \
    libCamera_ov02b1bdepthsunny2mipiraw_Default_Preview \
    libCamera_ov02b1bdepthsunny2mipiraw_portrait_Capture_depth \
    libCamera_ov02b1bdepthsunny2mipiraw_portrait_preview_depth \
    libCamera_ov02b1bdepthsunnymipiraw_Default_Capture \
    libCamera_ov02b1bdepthsunnymipiraw_Default_Preview \
    libCamera_ov02b1bdepthsunnymipiraw_portrait_Capture_depth \
    libCamera_ov02b1bdepthsunnymipiraw_portrait_preview_depth \
    libCamera_ov02b1bdepthtrulymipiraw_Default_Capture \
    libCamera_ov02b1bdepthtrulymipiraw_Default_Preview \
    libCamera_ov02b1bdepthtrulymipiraw_portrait_Capture_depth \
    libCamera_ov02b1bdepthtrulymipiraw_portrait_preview_depth \
    libCamera_ov64b40mainaacmipiraw_3rd_Capture \
    libCamera_ov64b40mainaacmipiraw_3rd_Preview \
    libCamera_ov64b40mainaacmipiraw_3rd_Preview_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_3rd_Preview_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_3rd_Video \
    libCamera_ov64b40mainaacmipiraw_Default_Face_Capture \
    libCamera_ov64b40mainaacmipiraw_Default_Face_Preview \
    libCamera_ov64b40mainaacmipiraw_Default_Scene_Capture \
    libCamera_ov64b40mainaacmipiraw_Default_Scene_Preview \
    libCamera_ov64b40mainaacmipiraw_Default_Video \
    libCamera_ov64b40mainaacmipiraw_Face_Capture \
    libCamera_ov64b40mainaacmipiraw_Face_Capture_64M \
    libCamera_ov64b40mainaacmipiraw_Face_Capture_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Face_Capture_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_Face_Preview \
    libCamera_ov64b40mainaacmipiraw_Face_Preview_64M \
    libCamera_ov64b40mainaacmipiraw_Face_Preview_Colorenhancement \
    libCamera_ov64b40mainaacmipiraw_Face_Preview_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Face_Preview_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_Flash_Capture \
    libCamera_ov64b40mainaacmipiraw_Flash_Preview \
    libCamera_ov64b40mainaacmipiraw_HDR_Capture \
    libCamera_ov64b40mainaacmipiraw_HDR_Capture_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_HDR_Capture_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_HDR_Capture_Zoom3 \
    libCamera_ov64b40mainaacmipiraw_HDR_Face_Capture \
    libCamera_ov64b40mainaacmipiraw_LLHDR_Capture \
    libCamera_ov64b40mainaacmipiraw_LLHDR_Capture_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_LLHDR_Capture_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_LLHDR_Capture_Zoom3 \
    libCamera_ov64b40mainaacmipiraw_LLHDR_Face_Capture \
    libCamera_ov64b40mainaacmipiraw_Panorama_Capture \
    libCamera_ov64b40mainaacmipiraw_Panorama_Preview \
    libCamera_ov64b40mainaacmipiraw_Portrait_Capture \
    libCamera_ov64b40mainaacmipiraw_Portrait_Preview \
    libCamera_ov64b40mainaacmipiraw_Professional_Capture \
    libCamera_ov64b40mainaacmipiraw_Professional_Capture_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Professional_Capture_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_Professional_Preview \
    libCamera_ov64b40mainaacmipiraw_Professional_Preview_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Professional_Preview_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_Scene_Capture \
    libCamera_ov64b40mainaacmipiraw_Scene_Capture_64M \
    libCamera_ov64b40mainaacmipiraw_Scene_Capture_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Scene_Capture_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_Scene_Capture_Zoom3 \
    libCamera_ov64b40mainaacmipiraw_Scene_Preview \
    libCamera_ov64b40mainaacmipiraw_Scene_Preview_64M \
    libCamera_ov64b40mainaacmipiraw_Scene_Preview_Colorenhancement \
    libCamera_ov64b40mainaacmipiraw_Scene_Preview_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Scene_Preview_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_SuperNight_Capture \
    libCamera_ov64b40mainaacmipiraw_SuperNight_Capture_Zoom \
    libCamera_ov64b40mainaacmipiraw_SuperNight_Face_Capture \
    libCamera_ov64b40mainaacmipiraw_SuperNight_Preview \
    libCamera_ov64b40mainaacmipiraw_SuperNight_Preview_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_SuperNight_Preview_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_Video_1080P_EIS \
    libCamera_ov64b40mainaacmipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_Video_720P_120fps \
    libCamera_ov64b40mainaacmipiraw_Video_720P_120fps_Zoom \
    libCamera_ov64b40mainaacmipiraw_Video_720P_EIS \
    libCamera_ov64b40mainaacmipiraw_Video_720P_EIS_Zoom1 \
    libCamera_ov64b40mainaacmipiraw_Video_720P_EIS_Zoom2 \
    libCamera_ov64b40mainaacmipiraw_XTS_Capture \
    libCamera_ov64b40mainaacmipiraw_XTS_Preview \
    libCamera_ov64b40mainofilmmipiraw_3rd_Capture \
    libCamera_ov64b40mainofilmmipiraw_3rd_Preview \
    libCamera_ov64b40mainofilmmipiraw_3rd_Preview_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_3rd_Preview_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_3rd_Video \
    libCamera_ov64b40mainofilmmipiraw_Default_Face_Capture \
    libCamera_ov64b40mainofilmmipiraw_Default_Face_Preview \
    libCamera_ov64b40mainofilmmipiraw_Default_Scene_Capture \
    libCamera_ov64b40mainofilmmipiraw_Default_Scene_Preview \
    libCamera_ov64b40mainofilmmipiraw_Default_Video \
    libCamera_ov64b40mainofilmmipiraw_Face_Capture \
    libCamera_ov64b40mainofilmmipiraw_Face_Capture_64M \
    libCamera_ov64b40mainofilmmipiraw_Face_Capture_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Face_Capture_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_Face_Preview \
    libCamera_ov64b40mainofilmmipiraw_Face_Preview_64M \
    libCamera_ov64b40mainofilmmipiraw_Face_Preview_Colorenhancement \
    libCamera_ov64b40mainofilmmipiraw_Face_Preview_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Face_Preview_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_Flash_Capture \
    libCamera_ov64b40mainofilmmipiraw_Flash_Preview \
    libCamera_ov64b40mainofilmmipiraw_HDR_Capture \
    libCamera_ov64b40mainofilmmipiraw_HDR_Capture_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_HDR_Capture_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_HDR_Capture_Zoom3 \
    libCamera_ov64b40mainofilmmipiraw_HDR_Face_Capture \
    libCamera_ov64b40mainofilmmipiraw_LLHDR_Capture \
    libCamera_ov64b40mainofilmmipiraw_LLHDR_Capture_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_LLHDR_Capture_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_LLHDR_Capture_Zoom3 \
    libCamera_ov64b40mainofilmmipiraw_LLHDR_Face_Capture \
    libCamera_ov64b40mainofilmmipiraw_Panorama_Capture \
    libCamera_ov64b40mainofilmmipiraw_Panorama_Preview \
    libCamera_ov64b40mainofilmmipiraw_Portrait_Capture \
    libCamera_ov64b40mainofilmmipiraw_Portrait_Preview \
    libCamera_ov64b40mainofilmmipiraw_Professional_Capture \
    libCamera_ov64b40mainofilmmipiraw_Professional_Capture_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Professional_Capture_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_Professional_Preview \
    libCamera_ov64b40mainofilmmipiraw_Professional_Preview_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Professional_Preview_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_Scene_Capture \
    libCamera_ov64b40mainofilmmipiraw_Scene_Capture_64M \
    libCamera_ov64b40mainofilmmipiraw_Scene_Capture_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Scene_Capture_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_Scene_Capture_Zoom3 \
    libCamera_ov64b40mainofilmmipiraw_Scene_Preview \
    libCamera_ov64b40mainofilmmipiraw_Scene_Preview_64M \
    libCamera_ov64b40mainofilmmipiraw_Scene_Preview_Colorenhancement \
    libCamera_ov64b40mainofilmmipiraw_Scene_Preview_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Scene_Preview_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_SuperNight_Capture \
    libCamera_ov64b40mainofilmmipiraw_SuperNight_Capture_Zoom \
    libCamera_ov64b40mainofilmmipiraw_SuperNight_Face_Capture \
    libCamera_ov64b40mainofilmmipiraw_SuperNight_Preview \
    libCamera_ov64b40mainofilmmipiraw_SuperNight_Preview_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_SuperNight_Preview_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_Video_1080P_EIS \
    libCamera_ov64b40mainofilmmipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_Video_720P_120fps \
    libCamera_ov64b40mainofilmmipiraw_Video_720P_120fps_Zoom \
    libCamera_ov64b40mainofilmmipiraw_Video_720P_EIS \
    libCamera_ov64b40mainofilmmipiraw_Video_720P_EIS_Zoom1 \
    libCamera_ov64b40mainofilmmipiraw_Video_720P_EIS_Zoom2 \
    libCamera_ov64b40mainofilmmipiraw_XTS_Capture \
    libCamera_ov64b40mainofilmmipiraw_XTS_Preview \
    libCamera_ov64b40mainsunnymipiraw_3rd_Capture \
    libCamera_ov64b40mainsunnymipiraw_3rd_Preview \
    libCamera_ov64b40mainsunnymipiraw_3rd_Preview_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_3rd_Preview_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_3rd_Video \
    libCamera_ov64b40mainsunnymipiraw_Default_Face_Capture \
    libCamera_ov64b40mainsunnymipiraw_Default_Face_Preview \
    libCamera_ov64b40mainsunnymipiraw_Default_Scene_Capture \
    libCamera_ov64b40mainsunnymipiraw_Default_Scene_Preview \
    libCamera_ov64b40mainsunnymipiraw_Default_Video \
    libCamera_ov64b40mainsunnymipiraw_Face_Capture \
    libCamera_ov64b40mainsunnymipiraw_Face_Capture_64M \
    libCamera_ov64b40mainsunnymipiraw_Face_Capture_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Face_Capture_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_Face_Preview \
    libCamera_ov64b40mainsunnymipiraw_Face_Preview_64M \
    libCamera_ov64b40mainsunnymipiraw_Face_Preview_Colorenhancement \
    libCamera_ov64b40mainsunnymipiraw_Face_Preview_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Face_Preview_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_Flash_Capture \
    libCamera_ov64b40mainsunnymipiraw_Flash_Preview \
    libCamera_ov64b40mainsunnymipiraw_HDR_Capture \
    libCamera_ov64b40mainsunnymipiraw_HDR_Capture_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_HDR_Capture_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_HDR_Capture_Zoom3 \
    libCamera_ov64b40mainsunnymipiraw_HDR_Face_Capture \
    libCamera_ov64b40mainsunnymipiraw_LLHDR_Capture \
    libCamera_ov64b40mainsunnymipiraw_LLHDR_Capture_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_LLHDR_Capture_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_LLHDR_Capture_Zoom3 \
    libCamera_ov64b40mainsunnymipiraw_LLHDR_Face_Capture \
    libCamera_ov64b40mainsunnymipiraw_Panorama_Capture \
    libCamera_ov64b40mainsunnymipiraw_Panorama_Preview \
    libCamera_ov64b40mainsunnymipiraw_Portrait_Capture \
    libCamera_ov64b40mainsunnymipiraw_Portrait_Preview \
    libCamera_ov64b40mainsunnymipiraw_Professional_Capture \
    libCamera_ov64b40mainsunnymipiraw_Professional_Capture_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Professional_Capture_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_Professional_Preview \
    libCamera_ov64b40mainsunnymipiraw_Professional_Preview_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Professional_Preview_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_Scene_Capture \
    libCamera_ov64b40mainsunnymipiraw_Scene_Capture_64M \
    libCamera_ov64b40mainsunnymipiraw_Scene_Capture_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Scene_Capture_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_Scene_Capture_Zoom3 \
    libCamera_ov64b40mainsunnymipiraw_Scene_Preview \
    libCamera_ov64b40mainsunnymipiraw_Scene_Preview_64M \
    libCamera_ov64b40mainsunnymipiraw_Scene_Preview_Colorenhancement \
    libCamera_ov64b40mainsunnymipiraw_Scene_Preview_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Scene_Preview_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_SuperNight_Capture \
    libCamera_ov64b40mainsunnymipiraw_SuperNight_Capture_Zoom \
    libCamera_ov64b40mainsunnymipiraw_SuperNight_Face_Capture \
    libCamera_ov64b40mainsunnymipiraw_SuperNight_Preview \
    libCamera_ov64b40mainsunnymipiraw_SuperNight_Preview_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_SuperNight_Preview_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_Video_1080P_EIS \
    libCamera_ov64b40mainsunnymipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_Video_720P_120fps \
    libCamera_ov64b40mainsunnymipiraw_Video_720P_120fps_Zoom \
    libCamera_ov64b40mainsunnymipiraw_Video_720P_EIS \
    libCamera_ov64b40mainsunnymipiraw_Video_720P_EIS_Zoom1 \
    libCamera_ov64b40mainsunnymipiraw_Video_720P_EIS_Zoom2 \
    libCamera_ov64b40mainsunnymipiraw_XTS_Capture \
    libCamera_ov64b40mainsunnymipiraw_XTS_Preview \
    libCamera_s5k4h7ultrasunnymipiraw_EIS_Video_1080P \
    libCamera_s5k4h7ultrasunnymipiraw_EIS_Video_720P \
    libCamera_s5k4h7ultrasunnymipiraw_Face_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_Face_Preview \
    libCamera_s5k4h7ultrasunnymipiraw_Flash_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_HDR_Face_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_HDR_Scene_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_LLHDR_Face_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_LLHDR_Scene_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_Portrait_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_Portrait_Preview \
    libCamera_s5k4h7ultrasunnymipiraw_Professional_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_Professional_Preview \
    libCamera_s5k4h7ultrasunnymipiraw_Scene_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_Scene_Preview \
    libCamera_s5k4h7ultrasunnymipiraw_SuperNightRaw_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_SuperNightRaw_Preview \
    libCamera_s5k4h7ultrasunnymipiraw_Video_1080P \
    libCamera_s5k4h7ultrasunnymipiraw_Video_720P \
    libCamera_s5k4h7ultrasunnymipiraw_Zoom1_Video_1080P \
    libCamera_s5k4h7ultrasunnymipiraw_Zoom1_Video_720P \
    libCamera_s5k4h7ultrasunnymipiraw_Zoom2_Video_1080P \
    libCamera_s5k4h7ultrasunnymipiraw_Zoom2_Video_720P \
    libCamera_s5k4h7ultrasunnymipiraw_Zoom_Capture \
    libCamera_s5k4h7ultrasunnymipiraw_Zoom_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_3rd_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_Face_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_Face_Capture_108M \
    libCamera_s5khm2sdmainofilmmipiraw_Face_Capture_CE \
    libCamera_s5khm2sdmainofilmmipiraw_Face_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_Flash_A_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_Flash_A_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_Flash_A_Preview_zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Flash_A_Preview_zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_HDR_Face_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_HDR_Face_Capture_CE \
    libCamera_s5khm2sdmainofilmmipiraw_HDR_Scene_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_HDR_Scene_Capture_CE \
    libCamera_s5khm2sdmainofilmmipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_LLHDR_Face_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_LLHDR_Scene_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_Panorama_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_QQ_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Capture_108M \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Capture_CE \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Capture_Professional \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Capture_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Capture_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Preview_FullScale \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Preview_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Preview_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Scene_Professional_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_SuperNightRaw_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_SuperNightRaw_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_SuperNightSE_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_60fps \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_EIS \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_1080P_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_120fps \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_120fps_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_120fps_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_EIS \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_EIS_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_EIS_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_Zoom1 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_720P_Zoom2 \
    libCamera_s5khm2sdmainofilmmipiraw_Video_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_WeChatQQ_Video \
    libCamera_s5khm2sdmainofilmmipiraw_WeChat_Preview \
    libCamera_s5khm2sdmainofilmmipiraw_XTS_Capture \
    libCamera_s5khm2sdmainofilmmipiraw_portrait_capture_full \
    libCamera_s5khm2sdmainofilmmipiraw_portrait_preview_full \
    libCamera_s5khm2sdmainsemcomipiraw_3rd_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_Face_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_Face_Capture_108M \
    libCamera_s5khm2sdmainsemcomipiraw_Face_Capture_CE \
    libCamera_s5khm2sdmainsemcomipiraw_Face_Preview \
    libCamera_s5khm2sdmainsemcomipiraw_Flash_A_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_Flash_A_Preview \
    libCamera_s5khm2sdmainsemcomipiraw_Flash_A_Preview_zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Flash_A_Preview_zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_HDR_Face_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_HDR_Face_Capture_CE \
    libCamera_s5khm2sdmainsemcomipiraw_HDR_Scene_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_HDR_Scene_Capture_CE \
    libCamera_s5khm2sdmainsemcomipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_LLHDR_Face_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_LLHDR_Scene_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_LLHDR_Scene_Capture_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_LLHDR_Scene_Capture_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Panorama_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_QQ_Preview \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Capture_108M \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Capture_CE \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Capture_Professional \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Capture_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Capture_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Preview \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Preview_FullScale \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Preview_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Preview_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Scene_Professional_Preview \
    libCamera_s5khm2sdmainsemcomipiraw_SuperNightRaw_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_SuperNightRaw_Preview \
    libCamera_s5khm2sdmainsemcomipiraw_SuperNightSE_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_60fps \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_EIS \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_1080P_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_120fps \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_120fps_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_120fps_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_EIS \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_EIS_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_EIS_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_Zoom1 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_720P_Zoom2 \
    libCamera_s5khm2sdmainsemcomipiraw_Video_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_WeChatQQ_Video \
    libCamera_s5khm2sdmainsemcomipiraw_WeChat_Preview \
    libCamera_s5khm2sdmainsemcomipiraw_XTS_Capture \
    libCamera_s5khm2sdmainsemcomipiraw_portrait_capture_full \
    libCamera_s5khm2sdmainsemcomipiraw_portrait_preview_full \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libNoFpsActor \
    libOpenCL \
    libQstAlgo \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTEECommon \
    lib_bsscore \
    libaaa_ltm \
    libaaa_ltmx \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libalCFR \
    libanc_dc_base \
    libanc_dc_plugin_xiaomi_v2 \
    libapu_mdw \
    libarcsoft_beautyshot \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_super_night_raw \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libasn1c_core \
    libasn1c_mapi \
    libasn1c_mdmi \
    libbluetooth_mtk \
    libbt-vendor \
    libc++_shared \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcamera_scene \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libcameracustom_all_sensor_modules \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libchromanr \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libdpframework \
    libdre \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libforkexecwrap \
    libformatter \
    libgamehdr \
    libged \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libgpu_aux \
    libgpud \
    libgpudataproducer \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libhdrvideo \
    libheichal \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libimgsensorca \
    libimsg_log \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libksensor \
    liblpcnr \
    libm4u \
    libmfllcore \
    libmiStereoFactoryRemapBasicLib \
    libmiStereoFactoryRemapLib \
    libmialgo_sd \
    libmialgo_utils \
    libmialgoengine \
    libmibokeh_mt6873 \
    libminiui \
    libmipc \
    libmmagent \
    libmml \
    libmnetlink_v104 \
    libmnl \
    libmpbase \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libneuralnetworks_sl_driver_mtk_legacy_prebuilt \
    libneuroeara \
    libneuron_adapter_mgvi \
    libnir_neon_driver \
    libnir_neon_driver_ndk.mtk.vndk \
    libnotifyaudiohal \
    liboemcrypto \
    libpixelflinger \
    libpq_prot \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librgbwlightsensor \
    librilfusion \
    librpc \
    libsensor_custom \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libsysenv \
    libteeclientjni \
    libteeclientjni@1.1 \
    libteei_daemon_vfs \
    libthha \
    libthhclient \
    libtlcWidevineModularDrm \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libvideofilter_only \
    libvidhance \
    libvidhance_calibration_tool \
    libvidhance_stabilizer \
    libwa_depth \
    libwa_refocus \
    libwa_rtdof \
    libwa_widelens_undistort \
    libwifi-hal-mtk \
    libwpfa \
    libwvaidl \
    libmtkcam_streaminfo_plugin-p1stt \
    ov02b1b_depth_sunny2_mipi_raw_IdxMgr \
    ov02b1b_depth_sunny2_mipi_raw_tuning \
    ov02b1b_depth_sunny_mipi_raw_IdxMgr \
    ov02b1b_depth_sunny_mipi_raw_tuning \
    ov02b1b_depth_truly_mipi_raw_IdxMgr \
    ov02b1b_depth_truly_mipi_raw_tuning \
    ov64b40_main_aac_mipi_raw_IdxMgr \
    ov64b40_main_aac_mipi_raw_tuning \
    ov64b40_main_ofilm_mipi_raw_IdxMgr \
    ov64b40_main_ofilm_mipi_raw_tuning \
    ov64b40_main_sunny_mipi_raw_IdxMgr \
    ov64b40_main_sunny_mipi_raw_tuning \
    s5k4h7_ultra_sunny_mipi_raw_IdxMgr \
    s5k4h7_ultra_sunny_mipi_raw_tuning \
    s5khm2sd_main_ofilm_mipi_raw_IdxMgr \
    s5khm2sd_main_ofilm_mipi_raw_tuning \
    s5khm2sd_main_semco_mipi_raw_IdxMgr \
    s5khm2sd_main_semco_mipi_raw_tuning \
    vendor.mediatek.hardware.apuware.utils-V1-ndk \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.mmagent-V1-ndk \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    vendor.microtrust.hardware.soter@1.0 \
    vendor.microtrust.hardware.thh@2.0 \
    wechat.beanpod \
    SoterService \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.tetheroffload-V1-service.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm-service.widevine.xml \
    manifest_apuware_utils_aidl.xml \
    manifest_media_c2_V1_2_default.xml \
    manifest_thh.xml \
    batterysecret \
    bp_kmsetkey_ca \
    ccci_mdinit \
    ccci_rpcd \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.drm-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.beanpod \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk-legacy \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.mmagent-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.microtrust.hardware.soter@1.0-service \
    vendor.microtrust.hardware.thh@2.0-service \
    vtservice_hidl \
    init_thh \
    ipsec_mon \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    mi_thermald \
    mnld \
    mt6660_calibration \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    rt5512_calibration \
    teei_daemon \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_stack \
    volte_ua \
    vpud \
    wlan_assistant \
    wmt_launcher \
    wmt_loader
